[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
seed_data_source_mutability = "JPzMSuJhdRAQVprukEXm4tkjXa6BHuhsqtaBQbU6e6R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
